#!/usr/bin/env bash
set -Eeuo pipefail

readonly WORKER_ENV=/etc/radar/worker.env
readonly RADAR_ROOT=/srv/radar
readonly APP_DIR=${RADAR_ROOT}/app
readonly CONFIG_DIR=${RADAR_ROOT}/config

if [[ ${EUID} -ne 0 ]]; then
  echo "bootstrap-host.sh must run as root" >&2
  exit 1
fi
if [[ ! -f ${WORKER_ENV} ]]; then
  echo "Missing ${WORKER_ENV}" >&2
  exit 1
fi

# The file is generated by CloudFormation from constrained parameters only.
# shellcheck disable=SC1090
source "${WORKER_ENV}"
: "${RADAR_DATA_VOLUME_ID:?RADAR_DATA_VOLUME_ID is required}"
: "${RADAR_REPO_URL:?RADAR_REPO_URL is required}"
: "${RADAR_REPO_BRANCH:?RADAR_REPO_BRANCH is required}"
: "${RADAR_STATE_BUCKET:?RADAR_STATE_BUCKET is required}"
: "${RADAR_AWS_REGION:?RADAR_AWS_REGION is required}"

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y --no-install-recommends \
  ca-certificates \
  curl \
  docker-compose-v2 \
  docker.io \
  git \
  jq \
  openssl \
  python3 \
  snapd \
  unzip

install_aws_cli() {
  if command -v aws >/dev/null 2>&1; then
    return
  fi

  local archive installer_dir
  installer_dir=$(mktemp -d /tmp/radar-awscli.XXXXXX)
  archive=${installer_dir}/awscliv2.zip
  curl --fail --location --silent --show-error \
    https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip \
    --output "${archive}"
  unzip -q "${archive}" -d "${installer_dir}"
  "${installer_dir}/aws/install"
  rm -rf "${installer_dir}"
}

install_tailscale() {
  install -d -m 0755 /usr/share/keyrings /etc/apt/sources.list.d
  curl --fail --location --silent --show-error \
    https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg \
    --output /usr/share/keyrings/tailscale-archive-keyring.gpg
  curl --fail --location --silent --show-error \
    https://pkgs.tailscale.com/stable/ubuntu/noble.tailscale-keyring.list \
    --output /etc/apt/sources.list.d/tailscale.list
  apt-get update
  apt-get install -y --no-install-recommends tailscale
  systemctl enable --now tailscaled.service
}

enable_ssm_agent() {
  if systemctl cat amazon-ssm-agent.service >/dev/null 2>&1; then
    systemctl enable --now amazon-ssm-agent.service
    return
  fi

  if ! snap list amazon-ssm-agent >/dev/null 2>&1; then
    snap install amazon-ssm-agent --classic
  fi
  systemctl enable --now snap.amazon-ssm-agent.amazon-ssm-agent.service
}

find_data_device() {
  local compact_volume_id candidate name serial
  compact_volume_id=${RADAR_DATA_VOLUME_ID//-/}
  candidate=/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_${compact_volume_id}
  if [[ -e ${candidate} ]]; then
    readlink -f "${candidate}"
    return 0
  fi

  while read -r name serial; do
    if [[ ${serial} == "${compact_volume_id}" ]]; then
      printf '%s\n' "${name}"
      return 0
    fi
  done < <(lsblk --nodeps --noheadings --output PATH,SERIAL)
  return 1
}

mount_data_volume() {
  local data_device filesystem_type filesystem_uuid mounted_uuid
  for _ in $(seq 1 180); do
    if data_device=$(find_data_device); then
      break
    fi
    sleep 5
  done
  if [[ -z ${data_device:-} ]]; then
    echo "Timed out waiting for retained EBS volume ${RADAR_DATA_VOLUME_ID}" >&2
    exit 1
  fi

  filesystem_type=$(blkid -o value -s TYPE "${data_device}" || true)
  if [[ -z ${filesystem_type} ]]; then
    mkfs.ext4 -F -L radar-data "${data_device}"
    filesystem_type=ext4
  fi
  filesystem_uuid=$(blkid -o value -s UUID "${data_device}")
  if [[ -z ${filesystem_uuid} ]]; then
    echo "Could not resolve a filesystem UUID for ${data_device}" >&2
    exit 1
  fi

  install -d -m 0755 "${RADAR_ROOT}"
  if mountpoint -q "${RADAR_ROOT}"; then
    mounted_uuid=$(findmnt --noheadings --output UUID "${RADAR_ROOT}" | xargs)
    if [[ ${mounted_uuid} != "${filesystem_uuid}" ]]; then
      echo "${RADAR_ROOT} is already mounted from an unexpected filesystem" >&2
      exit 1
    fi
  else
    if ! awk -v target="UUID=${filesystem_uuid}" '$1 == target { found = 1 } END { exit !found }' /etc/fstab; then
      printf 'UUID=%s %s %s defaults,nofail 0 2\n' \
        "${filesystem_uuid}" "${RADAR_ROOT}" "${filesystem_type}" >> /etc/fstab
    fi
    mount "${RADAR_ROOT}"
  fi
}

configure_docker() {
  systemctl stop docker.service docker.socket 2>/dev/null || true
  install -d -m 0711 "${RADAR_ROOT}/docker" /etc/docker
  python3 - /etc/docker/daemon.json "${RADAR_ROOT}/docker" <<'PY'
import json
import os
import sys
from pathlib import Path

path = Path(sys.argv[1])
data_root = sys.argv[2]
settings = json.loads(path.read_text()) if path.exists() else {}
settings["data-root"] = data_root
temporary = path.with_suffix(".tmp")
temporary.write_text(json.dumps(settings, indent=2, sort_keys=True) + "\n")
os.chmod(temporary, 0o644)
os.replace(temporary, path)
PY
  systemctl enable --now docker.service
}

checkout_repository() {
  install -d -m 0755 "${RADAR_ROOT}"
  if [[ -d ${APP_DIR}/.git ]]; then
    if [[ -n $(git -C "${APP_DIR}" status --porcelain --untracked-files=no) ]]; then
      echo "Tracked changes exist in ${APP_DIR}; refusing to overwrite a machine deployment" >&2
      exit 1
    fi
    git -C "${APP_DIR}" fetch --prune origin "${RADAR_REPO_BRANCH}"
    git -C "${APP_DIR}" checkout "${RADAR_REPO_BRANCH}"
    git -C "${APP_DIR}" merge --ff-only "origin/${RADAR_REPO_BRANCH}"
  elif [[ -e ${APP_DIR} ]]; then
    echo "${APP_DIR} exists but is not a Git checkout" >&2
    exit 1
  else
    git clone --branch "${RADAR_REPO_BRANCH}" "${RADAR_REPO_URL}" "${APP_DIR}"
  fi
}

create_runtime_environment() {
  install -d -m 0700 "${CONFIG_DIR}"
  if [[ ! -f ${CONFIG_DIR}/runtime.env ]]; then
    local postgres_password
    postgres_password=$(openssl rand -hex 32)
    umask 077
    printf '%s\n' \
      'POSTGRES_DB=yc_radar' \
      'POSTGRES_USER=yc_radar' \
      "POSTGRES_PASSWORD=${postgres_password}" \
      'OPENAI_API_KEY=' \
      'FIRECRAWL_API_KEY=' \
      > "${CONFIG_DIR}/runtime.env"
  fi

  install -d -m 0755 \
    "${APP_DIR}/data/local" \
    "${APP_DIR}/data/local/runs" \
    "${APP_DIR}/data/local/debug" \
    "${APP_DIR}/data/local/cache" \
    "${RADAR_ROOT}/state/jobs" \
    "${RADAR_ROOT}/backups"
  chown -R 1000:1000 "${APP_DIR}/data/local" "${APP_DIR}/data/snapshots"
}

install_worker_services() {
  install -m 0755 "${APP_DIR}/deploy/aws/deploy-host.sh" /usr/local/sbin/radar-deploy
  install -m 0755 "${APP_DIR}/deploy/aws/run-job.sh" /usr/local/sbin/radar-run-job
  install -m 0755 "${APP_DIR}/deploy/aws/jobctl.sh" /usr/local/sbin/radar-jobctl
  install -m 0755 \
    "${APP_DIR}/deploy/aws/configure-tailscale-exit-node.sh" \
    /usr/local/sbin/radar-configure-tailscale-exit-node
  install -m 0644 "${APP_DIR}/deploy/systemd/radar-deploy.service" /etc/systemd/system/radar-deploy.service
  install -m 0644 "${APP_DIR}/deploy/systemd/radar-job@.service" /etc/systemd/system/radar-job@.service
  /usr/local/sbin/radar-configure-tailscale-exit-node
  systemctl daemon-reload
  systemctl enable radar-deploy.service
}

install_aws_cli
install_tailscale
enable_ssm_agent
mount_data_volume
configure_docker
checkout_repository
create_runtime_environment
install_worker_services
systemctl start radar-deploy.service

echo "YC Radar worker bootstrap completed"
